### ISSUE TITLE
unable to load library in angular2 application

### ISSUE THREAD

**Issue by messerbill** [nekken/ng2-fullcalendar#13]
Hi,
I've been trying to get angular2-fullcalendar working in my angular2 application for two days now...i really have no idea why its not working....i am also quite new to typescript and angular2. So what i did:

i run 

`npm install angular2-fullcalendar --save`

afterwards i added the following line to **app.module.ts**:
`import { CalendarComponent } from "angular2-fullcalendar/src/calendar/calendar";`

`
@NgModule({
    imports: [BrowserModule],
    declarations: [AppComponent, HeadbarComponent, NavigationComponent, CalendarComponent],
    bootstrap: [AppComponent]
})`

my tsconfig.json looks like:
`{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true
  }
}
`
my application produces the following error:

> GET http://localhost:3000/angular2-fullcalendar/src/calendar/calendar 404 (Not Found)
scheduleTask @ zone.js:1645
ZoneDelegate.scheduleTask @ zone.js:255
Zone.scheduleMacroTask @ zone.js:168
(anonymous) @ zone.js:1669
send @ VM322:3
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:536
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:242
Zone.run @ zone.js:113
(anonymous) @ zone.js:520
ZoneDelegate.invokeTask @ zone.js:275
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:418
ZoneTask.invoke @ zone.js:349
(index):25 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/angular2-fullcalendar/src/calendar/calendar
	Error: XHR error (404 Not Found) loading http://localhost:3000/angular2-fullcalendar/src/calendar/calendar
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:889:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33) [<root>]
	Error loading http://localhost:3000/angular2-fullcalendar/src/calendar/calendar as "angular2-fullcalendar/src/calendar/calendar" from http://localhost:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:889:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33) [<root>]
	Error loading http://localhost:3000/angular2-fullcalendar/src/calendar/calendar as "angular2-fullcalendar/src/calendar/calendar" from http://localhost:3000/app/app.module.js
(anonymous) @ (index):25
ZoneDelegate.invoke @ zone.js:242
Zone.run @ zone.js:113
(anonymous) @ zone.js:520
ZoneDelegate.invokeTask @ zone.js:275
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:418
ZoneTask.invoke @ zone.js:349

at first i thought, it is the wrong path, so i added a "node_modules/" to the beginning of the path. This made the path look correctly, but i still received the same error. I am pretty sure that i did everything correct, i also updated node and npm...what is going wrong here?

best regards,
Ole

**Comment by messerbill** [comment]
the problem still exists....my IDE does find the lib, but my server does not. Is this an systemJs bug? or angular2 bug?

**Comment by kepner03** [comment]
Try this:

add the following to your systemjs.config.js  
```
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
     'ng2-fullcalendar': 'npm:angular2-fullcalendar/src/calendar/calendar.js',
      'jquery': 'npm:angular2-fullcalendar/node_modules/fullcalendar/node_modules/jquery/dist/jquery.js',
      'fullcalendar': 'npm:angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.js',
      'moment': 'npm:angular2-fullcalendar/node_modules/fullcalendar/node_modules/moment/moment.js'
   },
   packages: {
      'ng2-fullcalendar':{ 
          defaultExtension: 'js'
       }
    }
});
})(this);
```
Than add it to your NgModules:  
```
import { CalendarComponent } from 'ng2-fullcalendar';

@NgModule({
    bootstrap: [ AppComponent ],
    declarations: [
       CalendarComponent
    ]
})
```

**Comment by messerbill** [comment]
i already tried it this way, in this case i recieve the following error:

> app/app.module.ts(6,35): error TS2307: Cannot find module 'ng2-fullcalendar'.

it neither works the way you explained, nor this way:

> import { CalendarComponent } from 'fullcalendar';

my actual system.config.js:

```
/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      'ng2-fullcalendar': 'npm:angular2-fullcalendar/src/calendar/calendar.js',
      'jquery': 'npm:angular2-fullcalendar/node_modules/fullcalendar/node_modules/jquery/dist/jquery.js',
      'fullcalendar': 'npm:angular2-fullcalendar/node_modules/fullcalendar/dist/fullcalendar.js',
      'moment': 'npm:angular2-fullcalendar/node_modules/fullcalendar/node_modules/moment/moment.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
      
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'ng2-fullcalendar':{ 
          defaultExtension: 'js'
       }
    }
  });
})(this);
```

while my module looks like:

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule, Routes } from '@angular/router';

import { AppComponent } from './components/app/app.component';
import { CalendarComponent } from 'ng2-fullcalendar'; <-- "Cannot find module 'ng2-fullcalendar'"

import { ActionbarComponent } from './components/actionbar/actionbar.component';
import { NavigationComponent } from './components/navigation/navigation.component';
import { DashboardComponent } from './components/dashboard/dashboard.component';
import { ProjectListComponent } from './components/project-list/project-list.component';
import { DynamicComponent } from './components/dynamic/dynamic.component';
import { SearchComponent } from './components/search/search.component';
import { SearchfilterComponent } from './components/searchfilter/searchfilter.component';
import { PaginationComponent } from './components/pagination/pagination.component';
import { TimeRecordingComponent } from './components/time-recording/time-recording.component';
import { TimelineComponent } from './components/time-recording/timeline/timeline.component';
//import { DateRangeComponent } from './components/time-recording/date-range/date-range.component';
import { AppointmentComponent } from './components/appointment/appointment.component';
import { ThreesixtyBathroomComponent } from './components/360bathroom/360bathroom.component';
import { BasicClaimsDataComponent } from './components/basic-claims-data/basic-claims-data.component';

@NgModule({
    imports: [BrowserModule, RouterModule.forRoot([
        {
            path: '',
            redirectTo: '/dashboard',
            pathMatch: 'full'
        },
        {
            path: 'project',
            component: ProjectListComponent
        },
        {
            path: 'dashboard',
            component: DashboardComponent
        },
        {
            path: 'timerecording',
            component: TimeRecordingComponent
        },
        {
            path: 'appointment',
            component: AppointmentComponent
        },
        {
            path: 'threesixtybathroom',
            component: ThreesixtyBathroomComponent
        },
        {
            path: 'basicclaimsdata',
            component: BasicClaimsDataComponent
        }
    ])],
    declarations: [
        AppComponent, 
        ActionbarComponent, 
        NavigationComponent, 
        ProjectListComponent, 
        DashboardComponent, 
        DynamicComponent, 
        SearchComponent, 
        SearchfilterComponent, 
        PaginationComponent,
        TimeRecordingComponent,
        AppointmentComponent,
        ThreesixtyBathroomComponent,
        TimelineComponent,
        //DateRangeComponent,
        CalendarComponent,
        BasicClaimsDataComponent
        ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by messerbill** [comment]
finally i got i to work using webpack....i have no idea why it was not working with systemjs. Anyway, my application now uses webpack and it works as expected....by the gods, this was painful

**Comment by saikiranmandhala** [comment]
@messerbill , Thanks for the comment on SO, I have been getting the same error (ng2-fullcalendar not found) I will try once again with System.JS over this weekend and will let you know. Thanks.

**Comment by dstran** [comment]
@messerbill, would you post your webpack solution? Thanks in advance!

**Comment by dstran** [comment]
Also, anyone has success using this with Google calendar?

**Comment by kprim** [comment]
im getting the same error and i dont want to switch to webpack. any suggestion ??

**Comment by messerbill** [comment]
@saikiranmandhala @dstran Here is my webpack solution:

You need to change the "module" attribute inside your tsconfig.json from 

> "module": "systemjs"
to 

> "module": "commonjs"

Afterwards set up your webpack configuration files. My setup looks like:
webpack.config.js:
`module.exports = require('./webpack.dev.js');`

webpack.dev.js:
```var webpackMerge = require('webpack-merge');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var commonConfig = require('./webpack.common.js');
var helpers = require('./helpers');
console.log("test")
module.exports = webpackMerge(commonConfig, {
  devtool: 'cheap-module-eval-source-map',

  output: {
    path: helpers.root('dist'),
    publicPath: 'http://localhost:3000/',
    filename: '[name].js',
    chunkFilename: '[id].chunk.js'
  },

  plugins: [
    new ExtractTextPlugin('[name].css')
  ],

  devServer: {
    historyApiFallback: true,
    stats: 'minimal'
  }
});
```
and my webpack.common.js:

```var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var helpers = require('./helpers');

module.exports = {
  entry: {
    'polyfills': './app/polyfills.ts',
    'vendor': './app/vendor.ts',
    'app': './app/main.ts'
  },

  resolve: {
    extensions: ['', '.ts', '.js']
  },

  module: {
    loaders: [
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader', 'angular2-template-loader']
      },
      {
        test: /\.html$/,
        loader: 'html'
      },
      { 
        test: /\.css$/, 
        loaders: ['to-string-loader', 'css-loader']
      },
      { test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.wav$|\.mp3$/, loader: require.resolve("file-loader") + "?name=../[path][name].[ext]"}
        
    ]
  },

  node: {
    fs: "empty"
  },

  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: ['app', 'vendor', 'polyfills']
    }),

    new HtmlWebpackPlugin({
      template: 'index.html'
    })
  ]
};
```

In your app.module.ts you can now simply do at the top of the file:
`import { CalendarComponent } from 'angular2-fullcalendar/src/calendar/calendar';`
afterwards add "CalendarComponent" into your declarations array.

I hope i could help you,
best regards,
Ole

**Comment by dstran** [comment]
Thanks messerbill!

I'm following the README but getting the following errors:

Can't bind to 'options' since it isn't a known property of 'angular2-fullcalendar'

and

'angular2-fullcalendar' is not a known element:


Template:
<angular2-fullcalendar [options]="calendarOptions"></angular2-fullcalendar>


Would you please paste your code? Thanks!

-------------

UPDATE:

Fixed by having 'CalendarComponent' declared above my component.
