### ISSUE TITLE
Update Calendar after ViewInit

### ISSUE THREAD

**Issue by shah-smit** [nekken/ng2-fullcalendar#23]
I need to get events from server, there after i can update my calendar. How may i proceed from there.

Event object:
`events: any [] : [];`

Angular Calander Options:
`calendarOptions: Options = {}`

`ngViewInit (){}`

getting data from server
...
updating the cal...

`updateCalander (){
this.calendarOptions.events = this
events;}`

I event tried using ViewChild and directly using Jquery to do it but it is not Woking. 

Can you suggest me something?

**Comment by eurolife** [comment]
same problem. can anyone help please?

**Comment by shah-smit** [comment]
@eurolife  I found the solution. Can you share me your component file, I can help you fix. Or you may want to look at t: https://plnkr.co/edit/DicnkFVFhpEwJlRFMnOY?p=preview

**Comment by eurolife** [comment]
Thanks! I've tried it but I get $(...).fullCalendar is not a function error.

**Comment by shah-smit** [comment]
Try adding `import * as $ from 'jquery';` at the import area of the component area.

**Comment by eurolife** [comment]
That worked! Thank you so much!
