### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by bipin244** [nekken/ng2-fullcalendar#3]
/angular2-fullcalendar/src/calendar/calendar 
return 404 not found error

**Comment by nekken** [comment]
are you using ionic2 or simply angular2?

please provide more info on your setup

**Comment by bipin244** [comment]
simple angular 2

**Comment by nekken** [comment]
Please follow the installation instructions or give me more details with the stack trace of the error

**Comment by elic28** [comment]
![1](https://cloud.githubusercontent.com/assets/21154179/21002572/0e740dbc-bd59-11e6-8414-0707546a52a6.png) @nekken here is the error
im using angular2 quick starter

**Comment by elic28** [comment]
Here is my error 
@nekken i alr follow the instruction
![1](https://cloud.githubusercontent.com/assets/21154179/21002672/8098b6d6-bd59-11e6-8b08-27acc694d366.png)

**Comment by mayankdev** [comment]
hey i m facing same issue
Error: XHR error (404 Not Found) loading http://localhost:3000/angular2-fullcalendar/src/calendar/calendar
	Error loading http://localhost:3000/angular2-fullcalendar/src/calendar/calendar as "angular2-fullcalendar/src/calendar/calendar" from http://localhost:3000/app/calender.component.js

**Comment by OlivierBrabanders** [comment]
@nekken I'm also having trouble with this issue while using ionic 2.
See stack trace of the error below:
> Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/home/olivierb/Git/uhapp/node_modules/angular2-fullcalendar/src/calendar/calendar.js'
    at Object.<anonymous> (main.js:134404)
    at __webpack_require__ (bootstrap 08fc6c6…:19)
    at Object.<anonymous> (main.js:119245)
    at __webpack_require__ (bootstrap 08fc6c6…:19)
    at Object.<anonymous> (main.js:153722)
    at __webpack_require__ (bootstrap 08fc6c6…:19)
    at bootstrap 08fc6c6…:65
    at bootstrap 08fc6c6…:65

I'm using the following setup:

> Ionic  Framework: 2.0.1
Ionic Native: 2.4.1
Ionic App Scripts: 1.1.1
Angular Core: 2.4.5
Angular Compiler CLI: 2.4.5
Node: 7.7.3
OS Platform: Linux 4.4
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

**Comment by JorgeSanchezGr** [comment]
Im having the same error, im trying to use it inside ionic2 

> Error: Module build failed: Error: ENOENT: no such file or directory, open 'ionic-project/node_modules/angular2-fullcalendar/src/calendar/calendar.js'
> 
> 
> Failed to load resource: the server responded with a status of 404 (Not Found)
> http://localhost:8100/node_modules/fullcalendar/dist/fullcalendar.min.css

I have followed the guide but I can't make it work.

Regards

**Comment by thegust** [comment]
Same error
