### ISSUE TITLE
Is there a possibility to adjust the locale ?

### ISSUE THREAD

**Issue by StammenKai** [nekken/ng2-fullcalendar#6]
@nekken 
Thank you for your great work.
I have a question about angular2-fullcalendar.
Is there a possibility to adjust the

>  **locale:** to **'de'**

 and if so how.

Thank you for your help.

Greetings from Germany

Kai

**Comment by nekken** [comment]
Hi Kai, yes you can

Just add it in the configs

https://fullcalendar.io/docs/text/locale/

here is an example from fullCalendar:

https://fullcalendar.io/js/fullcalendar-3.1.0/demos/locales.html

Hope it helps

Ken

**Comment by StammenKai** [comment]
Thanks for help.
