### ISSUE TITLE
How do you manipulate the calendar?

### ISSUE THREAD

**Issue by chrischarlton001** [nekken/ng2-fullcalendar#9]
Hi - a great piece of work. I have this loading in Angular 2 (in an Ionic2 web page) and can adjust the options nicely. However, how do I add /remove events and generally access the calendar? With angular1 you reference the calendar with the following type of syntax:

$('#cal').fullCalendar('action',data)..
where cal refers to the id='cal' in the HTML (in the DOM).

What is the equivalent for referencing the calendar here? I have used
<angular2-fullcalendar [options]="calendarOptions"></angular2-fullcalendar>
as per your documentation which instantiates it nicely... but I don't know how then to access the instance. I.e. I need to knwo the syntax to do the equivalent of $('#cal').fullCalendar('action',data).. 
Thanks
Chris

**Comment by tomasklima** [comment]
Try just `$('angular2-fullcalendar').fullCalendar('action',data)`.

Alternatively, you can assign id and select the calendar via id:

```
<angular2-fullcalendar [options]="calendarOptions" id="myCalendar">

$('#myCalendar').fullCalendar('action',data)
```

**Comment by shah-smit** [comment]
I can only add events after i have got the data from the server. How May I update the events.

For example 
```
event: any = [ {
            title: 'All Day Event',
            start: '2017-02-20'
          },
          {
            title: 'Long Event',
            start: '2017-02-21',
            end: '2017-02-22'
          }];
```

And then I need to update the calendar: I am trying to the below but nothing is happening.

`$('#mycal').fullCalendar('updateEvents',this.event)`

And here is my html 

`<angular2-fullcalendar [options]="calendarOptions" id="mycal"></angular2-fullcalendar>`

Would appreciate help!
